export default {
  GOODS_CREATE: "GOODS_CREATE",
  GOODS_UPDATE: "GOODS_UPDATE",
  GOODS_DELETE: "GOODS_DELETE",
  GOODS_LOAD: "GOODS_LOAD",
  GOODS_ARRIVED: "GOODS_ARRIVED",
  GOODS_FIND_BY_CODE: "GOODS_FIND_BY_CODE",
  GOODS_FIND_BY_CODE_ARRIVED: "GOODS_FIND_BY_CODE_ARRIVED"
};
